export const dailyQuotes = [
  { author: "Albert Einstein", quote: "Life is like riding a bicycle. To keep your balance, you must keep moving." },
  { author: "Maya Angelou", quote: "You will face many defeats in life, but never let yourself be defeated." },
  { author: "Marcus Aurelius", quote: "You have power over your mind — not outside events. Realize this, and you will find strength." },
  { author: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop." },
  { author: "Oscar Wilde", quote: "Be yourself; everyone else is already taken." },
  { author: "Socrates", quote: "An unexamined life is not worth living." },
  { author: "Ralph Waldo Emerson", quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us." },
  { author: "Helen Keller", quote: "Keep your face to the sunshine and you cannot see a shadow." },
  { author: "Aristotle", quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit." },
  { author: "Friedrich Nietzsche", quote: "That which does not kill us makes us stronger." },

  { author: "Lao Tzu", quote: "A journey of a thousand miles begins with a single step." },
  { author: "Abraham Lincoln", quote: "Whatever you are, be a good one." },
  { author: "Mark Twain", quote: "The secret of getting ahead is getting started." },
  { author: "Seneca", quote: "Luck is what happens when preparation meets opportunity." },
  { author: "Buddha", quote: "What we think, we become." },
  { author: "Leonardo da Vinci", quote: "Learning never exhausts the mind." },
  { author: "Steve Jobs", quote: "Stay hungry, stay foolish." },
  { author: "Eleanor Roosevelt", quote: "Do one thing every day that scares you." },
  { author: "Walt Disney", quote: "The way to get started is to quit talking and begin doing." },
  { author: "Dalai Lama", quote: "Happiness is not something ready-made. It comes from your own actions." },

  { author: "Epictetus", quote: "It’s not what happens to you, but how you react to it that matters." },
  { author: "Plato", quote: "Courage is knowing what not to fear." },
  { author: "Henry Ford", quote: "Whether you think you can, or you think you can’t—you’re right." },
  { author: "Rumi", quote: "Where there is ruin, there is hope for a treasure." },
  { author: "Johann Wolfgang von Goethe", quote: "Whatever you can do or dream you can, begin it." },
  { author: "James Clear", quote: "Every action you take is a vote for the person you wish to become." },
  { author: "Napoleon Hill", quote: "Success comes to those who become success conscious." },
  { author: "Benjamin Franklin", quote: "An investment in knowledge pays the best interest." },
  { author: "Sun Tzu", quote: "In the midst of chaos, there is also opportunity." },
  { author: "George Bernard Shaw", quote: "Life isn’t about finding yourself. Life is about creating yourself." },

  { author: "Thomas Edison", quote: "I have not failed. I've just found 10,000 ways that won't work." },
  { author: "Marie Curie", quote: "Nothing in life is to be feared; it is only to be understood." },
  { author: "J.K. Rowling", quote: "It is our choices that show what we truly are, far more than our abilities." },
  { author: "Bruce Lee", quote: "Adapt what is useful, reject what is useless, and add what is specifically your own." },
  { author: "Viktor Frankl", quote: "When we are no longer able to change a situation, we are challenged to change ourselves." },
  { author: "Paulo Coelho", quote: "When you want something, all the universe conspires in helping you to achieve it." },
  { author: "Alan Watts", quote: "The only way to make sense out of change is to plunge into it." },
  { author: "Peter Drucker", quote: "The best way to predict the future is to create it." },
  { author: "Wayne Dyer", quote: "If you change the way you look at things, the things you look at change." },
  { author: "Zig Ziglar", quote: "You don’t have to be great to start, but you have to start to be great." },

  { author: "Tony Robbins", quote: "The only limit to your impact is your imagination and commitment." },
  { author: "John Wooden", quote: "Do not let what you cannot do interfere with what you can do." },
  { author: "Oprah Winfrey", quote: "The biggest adventure you can take is to live the life of your dreams." },
  { author: "Stephen Covey", quote: "I am not a product of my circumstances. I am a product of my decisions." },
  { author: "Jim Rohn", quote: "Discipline is the bridge between goals and accomplishment." },
  { author: "Brene Brown", quote: "Vulnerability is not weakness; it is our greatest measure of courage." },
  { author: "Charles Darwin", quote: "It is not the strongest of the species that survive, but the most adaptable." },
  { author: "Seth Godin", quote: "The cost of being wrong is less than the cost of doing nothing." },
  { author: "Robin Sharma", quote: "Small daily improvements lead to stunning results." },
  { author: "Eckhart Tolle", quote: "Realize deeply that the present moment is all you ever have." },

  { author: "Will Smith", quote: "The separation of talent and skill is one of the greatest misunderstood concepts." },
  { author: "Dale Carnegie", quote: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success." },
  { author: "Michelangelo", quote: "If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful." },
  { author: "James Baldwin", quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced." },
  { author: "Andrew Carnegie", quote: "The secret of my success is that we have gone to exceptional lengths to hire the best people." },
  { author: "Milton Berle", quote: "If opportunity doesn’t knock, build a door." },
  { author: "Henry David Thoreau", quote: "Go confidently in the direction of your dreams. Live the life you have imagined." },
  { author: "Coco Chanel", quote: "Success is most often achieved by those who don’t know that failure is inevitable." },
  { author: "George Eliot", quote: "It is never too late to be what you might have been." },
  { author: "Jack Ma", quote: "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine." },

  { author: "Ray Dalio", quote: "Pain plus reflection equals progress." },
  { author: "Elon Musk", quote: "When something is important enough, you do it even if the odds are not in your favor." },
  { author: "Naval Ravikant", quote: "Desire is a contract you make with yourself to be unhappy until you get what you want." },
  { author: "Jeff Bezos", quote: "If you double the number of experiments you do per year, you’re going to double your inventiveness." },
  { author: "Reid Hoffman", quote: "If you are not embarrassed by the first version of your product, you launched too late." },
  { author: "Sam Altman", quote: "The best ideas come from problems you personally experience." },
  { author: "Paul Graham", quote: "Do things that don’t scale." },
  { author: "Peter Thiel", quote: "Brilliant thinking is rare, but courage is in even shorter supply." },
  { author: "Sheryl Sandberg", quote: "Done is better than perfect." },
  { author: "Susan Cain", quote: "There’s zero correlation between being the best talker and having the best ideas." },

  { author: "Malcolm X", quote: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today." },
  { author: "Nelson Mandela", quote: "It always seems impossible until it’s done." },
  { author: "Desmond Tutu", quote: "Do your little bit of good where you are; it’s those little bits that overwhelm the world." },
  { author: "Anne Frank", quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world." },
  { author: "Vince Lombardi", quote: "Winners never quit, and quitters never win." },
  { author: "Michael Jordan", quote: "I've failed over and over and over again in my life. And that is why I succeed." },
  { author: "Serena Williams", quote: "Every woman's success should be an inspiration to another." },
  { author: "Muhammad Ali", quote: "Don’t count the days; make the days count." },
  { author: "Usain Bolt", quote: "Worries bring nothing. I focus on my goals." },
  { author: "Kobe Bryant", quote: "The moment you give up is the moment you let someone else win." },

  { author: "Aristotle Onassis", quote: "The secret of success is to know something nobody else knows." },
  { author: "Franklin D. Roosevelt", quote: "The only limit to our realization of tomorrow is our doubts of today." },
  { author: "George Patton", quote: "Success is how high you bounce when you hit bottom." },
  { author: "Hannah Arendt", quote: "Thinking without banisters is dangerous—but necessary." },
  { author: "Carl Jung", quote: "Who looks outside, dreams; who looks inside, awakes." },
  { author: "Joseph Campbell", quote: "The cave you fear to enter holds the treasure you seek." },
  { author: "Anaïs Nin", quote: "Life shrinks or expands in proportion to one’s courage." },
  { author: "Haruki Murakami", quote: "Pain is inevitable. Suffering is optional." },
  { author: "Fyodor Dostoevsky", quote: "The soul is healed by being with children." },
  { author: "Leo Tolstoy", quote: "Everyone thinks of changing the world, but no one thinks of changing himself." },

  { author: "Simone de Beauvoir", quote: "Change your life today. Don’t gamble on the future, act now." },
  { author: "Albert Camus", quote: "In the depth of winter, I finally learned that within me there lay an invincible summer." },
  { author: "Jean-Paul Sartre", quote: "Freedom is what you do with what’s been done to you." },
  { author: "George Orwell", quote: "In a time of deceit telling the truth is a revolutionary act." },
  { author: "Aldous Huxley", quote: "Experience is not what happens to you; it is what you do with what happens to you." },
  { author: "Virginia Woolf", quote: "You cannot find peace by avoiding life." },
  { author: "Ernest Hemingway", quote: "The best way to find out if you can trust somebody is to trust them." },
  { author: "J.R.R. Tolkien", quote: "All we have to decide is what to do with the time that is given us." },
  { author: "C.S. Lewis", quote: "You are never too old to set another goal or to dream a new dream." },
  { author: "Antoine de Saint-Exupéry", quote: "A goal without a plan is just a wish." },

  { author: "Victor Hugo", quote: "Even the darkest night will end and the sun will rise." },
  { author: "Pablo Picasso", quote: "Action is the foundational key to all success." },
  { author: "Salvador Dalí", quote: "Have no fear of perfection—you’ll never reach it." },
  { author: "Andy Warhol", quote: "They always say time changes things, but you actually have to change them yourself." },
  { author: "Frida Kahlo", quote: "At the end of the day, we can endure much more than we think we can." },
  { author: "Banksy", quote: "If you get tired, learn to rest, not to quit." },
  { author: "David Goggins", quote: "Suffering is the true test of life." },
  { author: "Jocko Willink", quote: "Discipline equals freedom." },
  { author: "Ryan Holiday", quote: "The obstacle in the path becomes the path." },
  { author: "Tim Ferriss", quote: "Focus on being productive instead of busy." },

  { author: "Cal Newport", quote: "Clarity about what matters provides clarity about what does not." },
  { author: "Simon Sinek", quote: "Working hard for something we don’t care about is called stress." },
  { author: "Adam Grant", quote: "The best way to succeed is to help others succeed." },
  { author: "Daniel Kahneman", quote: "Nothing in life is as important as you think it is while you are thinking about it." },
  { author: "Yuval Noah Harari", quote: "Change is the only constant." },
  { author: "Noam Chomsky", quote: "Optimism is a strategy for making a better future." },
  { author: "Stephen Hawking", quote: "Intelligence is the ability to adapt to change." },
  { author: "Neil deGrasse Tyson", quote: "The good thing about science is that it’s true whether or not you believe in it." },
  { author: "Richard Feynman", quote: "What I cannot create, I do not understand." },
  { author: "Carl Sagan", quote: "Somewhere, something incredible is waiting to be known." },

  { author: "Alan Turing", quote: "Those who can imagine anything, can create the impossible." },
  { author: "Grace Hopper", quote: "The most dangerous phrase is: 'We’ve always done it this way.'" },
  { author: "Ada Lovelace", quote: "That brain of mine is something more than merely mortal." },
  { author: "Linus Torvalds", quote: "Talk is cheap. Show me the code." },
  { author: "Steve Wozniak", quote: "Never trust a computer you can’t throw out a window." },
  { author: "Bill Gates", quote: "Patience is a key element of success." },
  { author: "Satya Nadella", quote: "Empathy makes you a better innovator." },
  { author: "Reed Hastings", quote: "Do not tolerate brilliant jerks." },
  { author: "Marc Andreessen", quote: "Strong views, loosely held." },
  { author: "Ben Horowitz", quote: "The hard thing about hard things is that there is no formula." },

  { author: "Shane Parrish", quote: "The most powerful way to change your life is to change what you think about." },
  { author: "Charlie Munger", quote: "Spend each day trying to be a little wiser than you were when you woke up." },
  { author: "Warren Buffett", quote: "The best investment you can make is in yourself." },
  { author: "Howard Marks", quote: "You can’t predict, but you can prepare." },
  { author: "Jack Welch", quote: "Face reality as it is, not as it was or as you wish it to be." },
  { author: "Mary Barra", quote: "It’s not about perfection. It’s about purpose." },
  { author: "Indra Nooyi", quote: "Leadership is hard to define, but easy to recognize." },
  { author: "Shonda Rhimes", quote: "Ditch the dream and be a doer." },
  { author: "Elizabeth Gilbert", quote: "You are allowed to be both a masterpiece and a work in progress." },
  { author: "Toni Morrison", quote: "If there’s a book you want to read, but it hasn’t been written yet, then you must write it." },

  { author: "Margaret Mead", quote: "Never doubt that a small group of thoughtful citizens can change the world." },
  { author: "Jane Goodall", quote: "What you do makes a difference, and you have to decide what kind of difference you want to make." },
  { author: "Rachel Carson", quote: "In nature, nothing exists alone." },
  { author: "E.O. Wilson", quote: "The real problem of humanity is the following: we have Paleolithic emotions." },
  { author: "Buckminster Fuller", quote: "You never change things by fighting the existing reality." },
  { author: "Marshall McLuhan", quote: "The medium is the message." },
  { author: "Peter Singer", quote: "Ethics is not a luxury." },
  { author: "Václav Havel", quote: "Hope is not optimism. It is the conviction that something makes sense." },
  { author: "Ralph Nader", quote: "The function of leadership is to produce more leaders." },
  { author: "Malala Yousafzai", quote: "One child, one teacher, one book, one pen can change the world." },

  { author: "Greta Thunberg", quote: "No one is too small to make a difference." },
  { author: "Aung San Suu Kyi", quote: "The only real prison is fear." },
  { author: "Thich Nhat Hanh", quote: "Peace is every step." },
  { author: "Pema Chödrön", quote: "Nothing ever goes away until it teaches us what we need to know." },
  { author: "Deepak Chopra", quote: "In the midst of movement and chaos, keep stillness inside of you." },
  { author: "Jon Kabat-Zinn", quote: "You can’t stop the waves, but you can learn to surf." },
  { author: "Byron Katie", quote: "When you argue with reality, you lose—but only 100% of the time." },
  { author: "Eckhart Tolle", quote: "Awareness is the greatest agent for change." },
  { author: "Wayne Gretzky", quote: "You miss 100% of the shots you don’t take." },
  { author: "Babe Ruth", quote: "Every strike brings me closer to the next home run." },

  { author: "Confucius", quote: "Wheresoever you go, go with all your heart." },
  { author: "Plutarch", quote: "Know how to listen, and you will profit even from those who talk badly." },
  { author: "Heraclitus", quote: "No man ever steps in the same river twice." },
  { author: "Democritus", quote: "Happiness resides not in possessions, and not in gold, happiness dwells in the soul." },
  { author: "Epicurus", quote: "Do not spoil what you have by desiring what you have not." },
  { author: "Cicero", quote: "Gratitude is not only the greatest of virtues, but the parent of all others." },
  { author: "Horace", quote: "Begin, be bold, and venture to be wise." },
  { author: "Ovid", quote: "Dripping water hollows out stone, not through force but through persistence." },
  { author: "Pliny the Elder", quote: "Fortune favors the bold." },
  { author: "Augustine of Hippo", quote: "Patience is the companion of wisdom." },

  { author: "Thomas Aquinas", quote: "Better to illuminate than merely to shine." },
  { author: "Francis Bacon", quote: "Knowledge itself is power." },
  { author: "Blaise Pascal", quote: "All of humanity's problems stem from man's inability to sit quietly in a room alone." },
  { author: "René Descartes", quote: "Conquer yourself rather than the world." },
  { author: "Baruch Spinoza", quote: "The highest activity a human being can attain is learning for understanding." },
  { author: "Immanuel Kant", quote: "Science is organized knowledge. Wisdom is organized life." },
  { author: "Arthur Schopenhauer", quote: "Talent hits a target no one else can hit; genius hits a target no one else can see." },
  { author: "Søren Kierkegaard", quote: "Life can only be understood backwards; but it must be lived forwards." },
  { author: "Friedrich Engels", quote: "An ounce of action is worth a ton of theory." },
  { author: "John Stuart Mill", quote: "Bad men need nothing more to compass their ends, than that good men should look on." },

  { author: "Ralph Waldo Emerson", quote: "The only person you are destined to become is the person you decide to be." },
  { author: "Henry James", quote: "Three things in human life are important: the first is to be kind; the second is to be kind." },
  { author: "William James", quote: "Act as if what you do makes a difference. It does." },
  { author: "Mark Twain", quote: "The two most important days in your life are the day you are born and the day you find out why." },
  { author: "Ambrose Bierce", quote: "Speak when you are angry and you will make the best speech you will ever regret." },
  { author: "Oscar Wilde", quote: "Experience is simply the name we give our mistakes." },
  { author: "George Santayana", quote: "Those who cannot remember the past are condemned to repeat it." },
  { author: "H.L. Mencken", quote: "For every complex problem there is an answer that is clear, simple, and wrong." },
  { author: "Albert Einstein", quote: "Strive not to be a success, but rather to be of value." },
  { author: "Nikola Tesla", quote: "The present is theirs; the future, for which I really worked, is mine." },

  { author: "Galileo Galilei", quote: "You cannot teach a man anything; you can only help him find it within himself." },
  { author: "Johannes Kepler", quote: "Truth is the daughter of time, not of authority." },
  { author: "Isaac Newton", quote: "What we know is a drop, what we don't know is an ocean." },
  { author: "Michael Faraday", quote: "Nothing is too wonderful to be true if it be consistent with the laws of nature." },
  { author: "Niels Bohr", quote: "An expert is a person who has made all the mistakes that can be made." },
  { author: "Max Planck", quote: "Science cannot solve the ultimate mystery of nature." },
  { author: "Werner Heisenberg", quote: "Not only is the universe stranger than we think, it is stranger than we can think." },
  { author: "Erwin Schrödinger", quote: "I don't like it, and I'm sorry I ever had anything to do with it." },
  { author: "Marie Curie", quote: "Be less curious about people and more curious about ideas." },
  { author: "Rosalind Franklin", quote: "Science and everyday life cannot and should not be separated." },

  { author: "Jane Austen", quote: "There is no charm equal to tenderness of heart." },
  { author: "Charles Dickens", quote: "Have a heart that never hardens, and a temper that never tires." },
  { author: "Herman Melville", quote: "It is better to fail in originality than to succeed in imitation." },
  { author: "Emily Dickinson", quote: "Forever is composed of nows." },
  { author: "Robert Frost", quote: "In three words I can sum up everything I've learned about life: it goes on." },
  { author: "Walt Whitman", quote: "Keep your face always toward the sunshine—and shadows will fall behind you." },
  { author: "Langston Hughes", quote: "Hold fast to dreams, for if dreams die, life is a broken-winged bird." },
  { author: "Virginia Woolf", quote: "Arrange whatever pieces come your way." },
  { author: "James Joyce", quote: "Mistakes are the portals of discovery." },
  { author: "George Bernard Shaw", quote: "Progress is impossible without change." },

  { author: "Mahatma Gandhi", quote: "Be the change that you wish to see in the world." },
  { author: "Rabindranath Tagore", quote: "You can't cross the sea merely by standing and staring at the water." },
  { author: "Jawaharlal Nehru", quote: "Culture is the widening of the mind and of the spirit." },
  { author: "Mother Teresa", quote: "Not all of us can do great things. But we can do small things with great love." },
  { author: "Dalai Lama", quote: "If you want others to be happy, practice compassion." },
  { author: "Thich Nhat Hanh", quote: "Smile, breathe, and go slowly." },
  { author: "Krishnamurti", quote: "It is no measure of health to be well adjusted to a profoundly sick society." },
  { author: "Alan Watts", quote: "Trying to define yourself is like trying to bite your own teeth." },
  { author: "Ram Dass", quote: "We’re all just walking each other home." },
  { author: "Lao Tzu", quote: "When I let go of what I am, I become what I might be." },

  { author: "Sun Tzu", quote: "Victorious warriors win first and then go to war." },
  { author: "Miyamoto Musashi", quote: "You must understand that there is more than one path to the top of the mountain." },
  { author: "Bruce Lee", quote: "Knowing is not enough, we must apply." },
  { author: "Jackie Chan", quote: "Don’t let circumstances control you." },
  { author: "Yoda", quote: "Do, or do not. There is no try." },
  { author: "George Lucas", quote: "You simply have to put one foot in front of the other." },
  { author: "Stan Lee", quote: "If you have an idea that you genuinely think is good, don’t let some idiot talk you out of it." },
  { author: "Hayao Miyazaki", quote: "Always believe in yourself. Do this and no matter where you are, you will have nothing to fear." },
  { author: "Akira Kurosawa", quote: "To be an artist means never to avert one's eyes." },
  { author: "David Lynch", quote: "The more you know yourself, the more patience you have for what you see in others." },

  { author: "Leonard Cohen", quote: "There is a crack in everything. That’s how the light gets in." },
  { author: "Bob Dylan", quote: "A man is a success if he gets up in the morning and gets to bed at night." },
  { author: "Johnny Cash", quote: "You build on failure. You use it as a stepping stone." },
  { author: "David Bowie", quote: "Always go a little further into the water than you feel you're capable of being in." },
  { author: "Prince", quote: "If you don't own your masters, your masters own you." },
  { author: "Aretha Franklin", quote: "Be your own artist, and always be confident in what you're doing." },
  { author: "Tupac Shakur", quote: "Reality is wrong. Dreams are for real." },
  { author: "Jay-Z", quote: "I’m not a businessman; I’m a business, man." },
  { author: "Kanye West", quote: "Believe in your flyness. Conquer your shyness." },
  { author: "Taylor Swift", quote: "People haven’t always been there for me but music always has." },

  { author: "Oprah Winfrey", quote: "Turn your wounds into wisdom." },
  { author: "Barack Obama", quote: "Change will not come if we wait for some other person." },
  { author: "Michelle Obama", quote: "Success isn’t about how much money you make." },
  { author: "Theodore Roosevelt", quote: "Do what you can, with what you have, where you are." },
  { author: "Abraham Lincoln", quote: "Whatever you are, be a good one." },
  { author: "Martin Luther King Jr.", quote: "The time is always right to do what is right." },
  { author: "Frederick Douglass", quote: "If there is no struggle, there is no progress." },
  { author: "Sojourner Truth", quote: "Truth is powerful and it prevails." },
  { author: "Harriet Tubman", quote: "Every great dream begins with a dreamer." },
  { author: "Rosa Parks", quote: "Each person must live their life as a model for others." }
];